name: CI / CD to development server

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/Iron'

    - name: Install dependencies
      run: npm install

    - name: Angular Build
      run: npm run build

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ vars.ftp_server }}
        username: ${{ vars.fftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: ./frontend/dist/skm/browser/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          update.php

          
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ vars.ftp_server }}
        username: ${{ vars.bftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: ./backend/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          passenger_wsgi.py
          
    - name: Run update on server
      run: wget http://${{ vars.domain }}/update.php
